; Copyright © Microsoft Corp.

[Theme]
; Windows - IDS_THEME_DISPLAYNAME_AERO_LIGHT
DisplayName=ÌÈÍÑÊ-Äåíü
ThemeId={E1B96BAB-93A0-4159-93A8-8AA64CC1913E}

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55

[Control Panel\Cursors]
AppStarting=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\AppStarting.ani
Arrow=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\Arrow.ani
Crosshair=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\cross.ani
Hand=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\Hand.ani
Help=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\Help.ani
IBeam=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\IBeam.ani
No=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\NO.ani
NWPen=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\Handwriting.ani
SizeAll=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\SizeAll.ani
SizeNESW=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\SizeNESW.ani
SizeNS=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\SizeNS.ani
SizeNWSE=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\SizeNWSE.ani
SizeWE=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\SizeWE.ani
UpArrow=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\UpArrow.ani
Wait=%SystemRoot%\Cursors\HUD Evolution Turquoise-EZEvolution\Wait.ani
DefaultValue=Turquoise-EZEvolution

[Control Panel\Desktop]
Wallpaper=%SystemRoot%\Web\Wallpaper\Windows\MINSK (11).jpg
Pattern=
MultimonBackgrounds=0
PicturePosition=2

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=1
ColorizationColor=0XC4736A02
SystemMode=Light
AppMode=Light
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=Panerai PAM01305 v2.scr

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
;SchemeName=@mmres.dll,-800

[Slideshow]
ImagesRootPIDL=IIAFA8BUg/E0gouOpBhoYjAArADMdmBAvMkOcBAAAAAAAAAAAAAAAAAAAAAAAAgUAEDAAAAAAESP8WDEgcVauR2b3NHA8AACAQAAv7r76MKFh0Dv1oCAAAQ6CAAAAAQAAAAAAAAAAAAAAAAAAAAAXBQaA4GAkBwbAcHAzBAAAYBAGBQMAAAAAAg76ApJQAyVlJGA0AACAQAAv7r76UKFurDkmoCAAAgDNAAAAAQAAAAAAAAAAAAAAAAAAAAAXBQZAIGAAAgEAgFAxAAAAAAAf0TUcCBIXFETMBVQ+FDAAAEAIAABA8uvurDkm8RPRxpKAAAAP0AAAAAABAAAAAAAAAAAAAAAAAAAAcFAhBAbAwGAwBQYAAHAlBgcAAAAYAQ6AEDAAAAAAYsT5mYEAcVauR2b3NHAABQCAQAAv77cOhpJG7UuJ6CAAAwFWAAAAAQAAAAAAAAAAAAAAAAAAAAAOTGxAcFApBgbAQGAvBwdAMHAAAgFAMJAAAwJA8uvFCAAAEzUQN1td66/Nyx/DFIjECkOjOXLpBAAAQGAAAAAfAAAAwCAAAwdAkGAuBAZA8GA3BwcA4CApBQbA0GAlBgcAMHApBgdAUGAjBwbA4GA0BgcA8GAsBAcAEGAuBQZAwGAfBwYAcHA1AgbAEDAoBgMAQHA4BQeAUGA3BQeAAAAAAAAAAAAAAgFAAAA

Interval=600000
Shuffle=1
