;C:\Program Files\WindowsApps
;PS C:\Users\MINSK> Get-AppxPackage | Select Name, PackageFullName
;Get-AppxPackage -AllUsers Microsoft.YourPhone | Remove-AppxPackage

Get-AppxPackage -AllUsers Microsoft.549981C3F5F10 | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.XboxIdentityProvider | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.XboxGameCallableUI | Remove-AppxPackage
Get-AppxPackage -AllUsers Windows.ParentalControls | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.ZuneVideo | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.ZuneMusic | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.YourPhone | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.XboxSpeechToTextOverlay | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.XboxGamingOverlay | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.Xbox.TCUI | Remove-AppxPackage
Get-AppxPackage -AllUsers MMicrosoft.XboxGameOverlay | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.Xbox.TCUI | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.XboxGameCallableUI | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.WindowsMaps | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.WindowsFeedbackHub | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.StorePurchaseApp | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.People | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.MicrosoftOfficeHub | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.GamingApp | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingWeather | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.BingNews | Remove-AppxPackage
Get-AppxPackage -AllUsers MicrosoftTeams | Remove-AppxPackage
Get-AppxPackage -AllUsers Microsoft.AAD.BrokerPlugin | Remove-AppxPackage
